FROM bitnami/node:16.17.0

# Create app directory
RUN mkdir -p /app
WORKDIR /app


# Bundle app source and install dep
COPY ["package.json", "yarn.lock", "/app/"]
RUN yarn install --frozen-lockfile

COPY . /app

ENV PORT 3000
ENV NUXT_PORT 3000
ENV NEST_PORT 3000

EXPOSE 3000

CMD ["node", "/app/node_modules/.bin/nest", "start", "--watch"]
